name: Publish Docker Image to GitHub Packages

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.AGITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: test my action
        uses: Domnic-Raj/publish@v1.0.1  

      - name: Build Docker image
        run: docker build -t ghcr.io/domnic-raj/my-docker-image:latest .

      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/domnic-raj/my-docker-image:latest
